/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestQrcodesRouteImport } from './routes/test-qrcodes'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicCableElidRouteImport } from './routes/api/public/cable.$elid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestQrcodesRoute = TestQrcodesRouteImport.update({
  id: '/test-qrcodes',
  path: '/test-qrcodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCableElidRoute = ApiPublicCableElidRouteImport.update({
  id: '/api/public/cable/$elid',
  path: '/api/public/cable/$elid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-qrcodes': typeof TestQrcodesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/cable/$elid': typeof ApiPublicCableElidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-qrcodes': typeof TestQrcodesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/cable/$elid': typeof ApiPublicCableElidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test-qrcodes': typeof TestQrcodesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/cable/$elid': typeof ApiPublicCableElidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/test-qrcodes' | '/api/public/health' | '/api/public/cable/$elid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test-qrcodes' | '/api/public/health' | '/api/public/cable/$elid'
  id:
    | '__root__'
    | '/'
    | '/test-qrcodes'
    | '/api/public/health'
    | '/api/public/cable/$elid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestQrcodesRoute: typeof TestQrcodesRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicCableElidRoute: typeof ApiPublicCableElidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-qrcodes': {
      id: '/test-qrcodes'
      path: '/test-qrcodes'
      fullPath: '/test-qrcodes'
      preLoaderRoute: typeof TestQrcodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cable/$elid': {
      id: '/api/public/cable/$elid'
      path: '/api/public/cable/$elid'
      fullPath: '/api/public/cable/$elid'
      preLoaderRoute: typeof ApiPublicCableElidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestQrcodesRoute: TestQrcodesRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicCableElidRoute: ApiPublicCableElidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
